#!/usr/bin/env python3
"""Build MEDIA-CHECKLIST.md from the MEDIA-TODO placeholders in the .mdx pages.

Usage:  python3 scripts/media-checklist.py          # rewrite MEDIA-CHECKLIST.md
        python3 scripts/media-checklist.py --check  # validate only, exit 1 on problems
"""
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
NOTE = re.compile(r'\{/\* MEDIA-TODO (screenshot|video) \| (\S+)\n(.*?)\*/\}\n\s*\{/\*\n(.*?)\*/\}', re.S)
items, problems, seen = [], [], {}
for dp, dn, fn in os.walk('.'):
    dn[:] = [d for d in dn if d not in ('.git', 'node_modules')]
    for f in sorted(fn):
        if not f.endswith('.mdx'): continue
        page = os.path.normpath(os.path.join(dp, f))
        s = open(page).read()
        found = list(NOTE.finditer(s))
        if s.count('MEDIA-TODO') != len(found):
            problems.append(f'{page}: {s.count("MEDIA-TODO") - len(found)} placeholder(s) do not match the format')
        live = re.sub(r'\{/\*.*?\*/\}', '', s, flags=re.S)
        for m in re.finditer(r'(?:src)="(/(?:images|videos)/[^"]+)"', live):
            if not os.path.exists(m.group(1).lstrip('/')):
                problems.append(f'{page}: live media points at missing file {m.group(1)}')
        for m in found:
            kind, path, note, frame = m.groups()
            fields = dict(re.findall(r'^\s*(Capture|Script|Route|Redact|Publish):\s*(.+?)\s*$', note, re.M))
            need = ['Capture', 'Route', 'Redact', 'Publish'] + (['Script'] if kind == 'video' else [])
            for k in need:
                if k not in fields: problems.append(f'{page}: {path} is missing "{k}:"')
            if f'src="{path}"' not in frame: problems.append(f'{page}: Frame src does not match {path}')
            alt = re.search(r'(?:alt|title)="([^"]+)"', frame)
            if not alt or len(alt.group(1).split()) < 5: problems.append(f'{page}: {path} needs a descriptive alt/title')
            if path in seen: problems.append(f'{path} used in both {seen[path]} and {page}')
            seen[path] = page
            items.append(dict(page=page, kind=kind, path=path, alt=alt.group(1) if alt else '',
                              ready=os.path.exists(path.lstrip('/')), **fields))
for p in problems: print('PROBLEM', p)
shots = [i for i in items if i['kind'] == 'screenshot']; vids = [i for i in items if i['kind'] == 'video']
print(f'{len(shots)} screenshots, {len(vids)} videos, {sum(i["ready"] for i in items)} file(s) already added, {len(problems)} problem(s)')
if '--check' in sys.argv: sys.exit(1 if problems else 0)
out = ['# Media checklist', '',
       'Generated by `python3 scripts/media-checklist.py`. Do not edit by hand.', '',
       f'**{len(shots)} screenshots and {len(vids)} videos** are waiting to be captured. Each one has an invisible',
       'placeholder in its page with a ready-made `<Frame>`. See [`images/README.md`](./images/README.md) for the workflow.', '',
       'A ticked box means the file exists at the path but the placeholder has not been uncommented yet.', '']
section = None
for i in sorted(items, key=lambda x: (x['page'], x['kind'], x['path'])):
    if i['page'] != section:
        section = i['page']; out += [f'## `{section}`', '']
    out.append(f'- [{"x" if i["ready"] else " "}] **{i["kind"]}** `{i["path"]}`')
    out.append(f'  - Capture: {i.get("Capture","")}')
    if i['kind'] == 'video': out.append(f'  - Script: {i.get("Script","")}')
    out.append(f'  - Route: `{i.get("Route","")}`')
    out.append(f'  - Redact: {i.get("Redact","")}')
    out.append(f'  - Alt text: {i["alt"]}')
    out.append('')
open('MEDIA-CHECKLIST.md', 'w').write('\n'.join(out))
sys.exit(1 if problems else 0)
